version: '3'

services:
    nginx:
        container_name: fitness_app_nginx
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        networks:
            - net
            - sso
            - component1
            - component2
            - component3
            - component4
            - component5

    frontend:
        container_name: fitness_app_frontend
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
            - frontend_node_modules:/usr/src/app/node_modules
        expose:
            - 3000
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks:
            - net
        stdin_open: true
        tty: true
    
    sso_backend:
        container_name: fitness_app_sso_backend
        build: ./sso/backend
        volumes:
            - ./sso/backend:/usr/src/app
            - sso_backend_node_modules:/usr/src/app/node_modules
        expose: 
            - 3001
        depends_on:
            - sso_database
        networks:
            - sso
            - net
        stdin_open: true
        tty: true

    sso_database:
        container_name: fitness_app_sso_database
        build: ./sso/database
        volumes:
            - sso_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=user_db
        networks:
            - sso
    
    comp1_backend:
        container_name: fitness_app_comp1_backend
        build: ./component1/backend
        volumes: 
            - ./component1/backend:/usr/src/app
            - comp1_backend_node_modules:/usr/src/app/node_modules
        expose: 
            - 3001
        depends_on:
            - comp1_database
        networks:
            - component1
            - net
        stdin_open: true
        tty: true

    comp1_database:
        container_name: fitness_app_comp1_database
        build: ./component1/database
        volumes:
            - component1_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=component1
        networks:
            - component1
    
    comp2_backend:
        container_name: fitness_app_comp2_backend
        build: ./component2/backend
        volumes: 
            - ./component2/backend:/usr/src/app
            - comp2_backend_node_modules:/usr/src/app/node_modules
        expose: 
            - 3001
        depends_on:
            - comp2_database
        networks:
            - component2
            - net
        stdin_open: true
        tty: true

    comp2_database:
        container_name: fitness_app_comp2_database
        build: ./component2/database
        volumes:
            - component2_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=component2
        networks:
            - component2
    
    comp3_backend:
        container_name: fitness_app_comp3_backend
        build: ./component3/backend
        volumes: 
            - ./component3/backend:/usr/src/app
            - comp3_backend_node_modules:/usr/src/app/node_modules
        expose: 
            - 3001
        depends_on:
            - comp3_database
        networks:
            - component3
            - net
        stdin_open: true
        tty: true

    comp3_database:
        container_name: fitness_app_comp3_database
        build: ./component3/database
        volumes:
            - component3_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=component3
        networks:
            - component3
    
    comp4_backend:
        container_name: fitness_app_comp4_backend
        build: ./component4/backend
        volumes: 
            - ./component4/backend:/usr/src/app
            - comp4_backend_node_modules:/usr/src/app/node_modules
        expose: 
            - 3001
        depends_on:
            - comp4_database
        networks:
            - component4
            - net
        stdin_open: true
        tty: true

    comp4_database:
        container_name: fitness_app_comp4_database
        build: ./component4/database
        volumes:
            - component4_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=component4
        networks:
            - component4
    
    comp5_backend:
        container_name: fitness_app_comp5_backend
        build: ./component5/backend
        volumes: 
            - ./component5/backend:/usr/src/app
            - comp5_backend_node_modules:/usr/src/app/node_modules
        expose: 
            - 3001
        depends_on:
            - comp5_database
        networks:
            - component5
            - net
        stdin_open: true
        tty: true

    comp5_database:
        container_name: fitness_app_comp5_database
        build: ./component5/database
        volumes:
            - component5_postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=component5
        networks:
            - component5

volumes:
    sso_postgres_data:
    frontend_node_modules:
    sso_backend_node_modules:
    component1_postgres_data:
    component2_postgres_data:
    component3_postgres_data:
    component4_postgres_data:
    component5_postgres_data:
    comp1_backend_node_modules:
    comp2_backend_node_modules:
    comp3_backend_node_modules:
    comp4_backend_node_modules:
    comp5_backend_node_modules:

networks:
    net:
        driver: bridge
    sso:
        driver: bridge
    component1:
        driver: bridge
    component2:
        driver: bridge
    component3:
        driver: bridge
    component4:
        driver: bridge
    component5:
        driver: bridge